CREATE SCHEMA USERNAME;

CREATE TABLE USERNAME.CARS (
  NUMBER_PLATE VARCHAR(6) NOT NULL PRIMARY KEY, 
  MAKE VARCHAR(20),
  MODEL VARCHAR(20), 
  YEAR_OF_MANUFACTURING INTEGER NOT NULL, 
  DAILY_RENTAL_FEE INTEGER NOT NULL, 
  LAST_SERVICE DATE NOT NULL,
  IN_SERVICE BOOLEAN NOT NULL, 
  PHOTO BOOLEAN NOT NULL
);

INSERT INTO USERNAME.CARS 
  (NUMBER_PLATE, MAKE, MODEL, YEAR_OF_MANUFACTURING, DAILY_RENTAL_FEE, LAST_SERVICE, IN_SERVICE, PHOTO) 
	VALUES ('MJJ391', 'Renault', 'Clio', 2010, 3000, DATE('2018-12-21'), true, false);
INSERT INTO USERNAME.CARS 
  (NUMBER_PLATE, MAKE, MODEL, YEAR_OF_MANUFACTURING, DAILY_RENTAL_FEE, LAST_SERVICE, IN_SERVICE, PHOTO) 
	VALUES ('ALF001', 'Alfa Romeo', 'Giulia 2.0', 2018, 20000, DATE('2018-06-08'), false, false);
INSERT INTO USERNAME.CARS 
  (NUMBER_PLATE, MAKE, MODEL, YEAR_OF_MANUFACTURING, DAILY_RENTAL_FEE, LAST_SERVICE, IN_SERVICE, PHOTO) 
	VALUES ('BUG002', 'Bugatti', 'Veyron', 2015, 200000, DATE('2018-02-23'), false, false);
INSERT INTO USERNAME.CARS 
  (NUMBER_PLATE, MAKE, MODEL, YEAR_OF_MANUFACTURING, DAILY_RENTAL_FEE, LAST_SERVICE, IN_SERVICE, PHOTO) 
	VALUES ('CIT003', 'Citroen', 'C5', 2007, 2000, DATE('2017-05-09'), false, false);
INSERT INTO USERNAME.CARS 
  (NUMBER_PLATE, MAKE, MODEL, YEAR_OF_MANUFACTURING, DAILY_RENTAL_FEE, LAST_SERVICE, IN_SERVICE, PHOTO) 
	VALUES ('FOR004', 'Ford', 'Mondeo', 2012, 5000, DATE('2018-10-05'), false, false);
INSERT INTO USERNAME.CARS 
  (NUMBER_PLATE, MAKE, MODEL, YEAR_OF_MANUFACTURING, DAILY_RENTAL_FEE, LAST_SERVICE, IN_SERVICE, PHOTO) 
	VALUES ('PEU005', 'Peugeot', '307', 2009, 2500, DATE('2019-01-04'), true, false);
INSERT INTO USERNAME.CARS 
  (NUMBER_PLATE, MAKE, MODEL, YEAR_OF_MANUFACTURING, DAILY_RENTAL_FEE, LAST_SERVICE, IN_SERVICE, PHOTO) 
	VALUES ('TES006', 'Tesla', 'S3', 2015, 35000, DATE('2018-01-26'), true, false);

CREATE TABLE USERNAME.CUSTOMERS (
  ID_CUSTOMER INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY(START WITH 1, INCREMENT BY 1), 
  NAME VARCHAR(60) NOT NULL, 
  ADDRESS VARCHAR(80), 
  PHONE VARCHAR(30)
);

INSERT INTO USERNAME.CUSTOMERS (NAME, ADDRESS, PHONE)
	VALUES ('Czakó Tamás', '1133 Budapest, Kárpát utca 33', '+36 70 3380854');
INSERT INTO USERNAME.CUSTOMERS (NAME, ADDRESS, PHONE)
	VALUES ('Micimackó', '100 holdas pagony', '()()()---()()()');
INSERT INTO USERNAME.CUSTOMERS (NAME, ADDRESS, PHONE)
	VALUES ('Kiszely Ágnes', '1083 Budapest, Tömő utca 40-46', '+36 20 2005016');
INSERT INTO USERNAME.CUSTOMERS (NAME, ADDRESS, PHONE)
	VALUES ('Mark Watney', 'Mars', '77-97-114-115 ');
INSERT INTO USERNAME.CUSTOMERS (NAME, ADDRESS, PHONE)
	VALUES ('Csécsei Mihály', 'Műszaki és Informatikai Főigazgatóság - Üzemeltetési Igazgatóság', '+36-(1)-411-6500 # 2414');

CREATE TABLE USERNAME.RENTS (
  ID_RENT INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY(START WITH 1, INCREMENT BY 1),
  ID_CUSTOMER INTEGER NOT NULL REFERENCES USERNAME.CUSTOMERS(ID_CUSTOMER),
  NUMBER_PLATE VARCHAR(6) NOT NULL REFERENCES USERNAME.CARS(NUMBER_PLATE), 
  BEGINNING_DATE DATE NOT NULL, 
  EXPECTED_RETURN_DATE DATE NOT NULL, 
  RETURN_DATE DATE DEFAULT NULL,
  DAILY_FEE INTEGER NOT NULL,
  PAID_FEE INTEGER DEFAULT 0
);
